#library("biomaRt")
diff_gene_deseq2 <-subset(res, pvalue < 0.05 & log2FoldChange > 1 | log2FoldChange < -1)
head(diff_gene_deseq2)
#mart <- useDataset("sscrofa_gene_ensembl", useMart("ensembl"))
#my_ensembl_gene_id <- row.names(diff_gene_deseq2)
#head(my_ensembl_gene_id)
#pig_symbols <- getBM(attributes = c('ensembl_gene_id','external_gene_name','description'),filters = 'ensembl_gene_id', values = my_ensembl_gene_id, mart = mart)
#head(pig_symbols)
#ensembl_gene_id <- rownames(diff_gene_deseq2)
#diff_gene_deseq2 <- cbind(ensembl_gene_id,diff_gene_deseq2)
#colnames(diff_gene_deseq2)[1]<-c("ensembl_gene_id")
#diff_name <-merge(diff_gene_deseq2, pig_symbols, by="ensembl_gene_id")
